// AUTO-GENERATED via tauri-specta on machines with GTK dev libs. This stub mirrors the shape.
// Regenerated by `pnpm --filter @yoube/desktop gen:contracts` (runs the Tauri binary in debug mode,
// which calls Builder::export -> ../src/bindings.ts). Overwritten on every debug build that reaches
// `run()`; this hand-written copy exists so the TypeScript side typechecks/builds in headless CI.

export type AppError = string;

export interface PingResponse {
  value: string;
}

export interface VideoSummary {
  id: string;
  title: string;
  channel_id: string;
  channel_title: string;
  duration_s?: number | null;
  view_count?: number | null;
  upload_date?: string | null;
  thumbnail_url?: string | null;
}

export interface Format {
  format_id: string;
  ext: string;
  url?: string | null;
  resolution?: string | null;
  fps?: number | null;
  vcodec?: string | null;
  acodec?: string | null;
  filesize?: number | null;
  tbr?: number | null;
  note?: string | null;
}

export interface Video {
  summary: VideoSummary;
  formats: Format[];
}

export interface Channel {
  id: string;
  title: string;
  description: string;
  thumb_url: string | null;
}

export interface Playlist {
  id: string;
  title: string;
  channel_id: string;
  items: VideoSummary[];
}

export enum Region {
  US,
  GB,
  EG,
  SA,
  DE,
  FR,
  JP,
  BR,
  IN,
  AU,
  CA,
  MX,
  ES,
  IT,
  RU,
  TR,
  ZA,
  NG,
  KR,
  AR,
}

export function ping(): Promise<PingResponse> {
  return Promise.resolve({ value: "pong" });
}

export function get_video(v: string): Promise<Video> {
  return Promise.resolve({
    summary: { id: v, title: "", channel_id: "", channel_title: "" },
    formats: [],
  });
}

export function related(_v: string): Promise<VideoSummary[]> {
  return Promise.resolve([]);
}

export function search(_q: string, _page: number): Promise<VideoSummary[]> {
  return Promise.resolve([]);
}

export function channel(id: string): Promise<Channel> {
  return Promise.resolve({ id, title: "", description: "", thumb_url: null });
}

export function channel_videos(_id: string, _page: number): Promise<VideoSummary[]> {
  return Promise.resolve([]);
}

export function playlist(id: string): Promise<Playlist> {
  return Promise.resolve({ id, title: "", channel_id: "", items: [] });
}

export function trending(_region: Region): Promise<VideoSummary[]> {
  return Promise.resolve([]);
}

// --- AccountService contracts (Task 2.2) ---
// Hand-stubbed mirroring crates/yoube-core/src/services/account.rs.
// Replaced by tauri-specta typegen on machines with the GTK stack.

export interface UserProfile {
  id: number;
  name: string;
  avatar_path: string | null;
}

export interface ChannelRef {
  id: string;
  title: string;
  thumb_url: string | null;
}

export interface AccountPlaylist {
  id: number;
  title: string;
  description: string | null;
  is_watch_later: boolean;
  is_liked: boolean;
  count: number;
}

export interface HistoryEntryView {
  video_id: string;
  title: string;
  channel_title: string | null;
  duration_s: number | null;
  thumb_url: string | null;
  watched_at: string;
  position_s: number;
}

export function current_user(): Promise<UserProfile> {
  return Promise.resolve({ id: 1, name: "yoube", avatar_path: null });
}

export function switch_user(_id: number): Promise<void> {
  return Promise.resolve();
}

export function create_user(name: string): Promise<UserProfile> {
  return Promise.resolve({ id: 1, name, avatar_path: null });
}

export function delete_user(_id: number): Promise<void> {
  return Promise.resolve();
}

export function subscriptions(): Promise<ChannelRef[]> {
  return Promise.resolve([]);
}

export function subscribe(
  _channel_id: string,
  _title: string,
  _thumb_url?: string | null,
): Promise<void> {
  return Promise.resolve();
}

export function unsubscribe(_channel_id: string): Promise<void> {
  return Promise.resolve();
}

export function playlists(): Promise<AccountPlaylist[]> {
  return Promise.resolve([]);
}

export function playlist_items(_id: number): Promise<VideoSummary[]> {
  return Promise.resolve([]);
}

export function playlist_add(_id: number, _video: VideoSummary): Promise<void> {
  return Promise.resolve();
}

export function playlist_remove(_id: number, _video_id: string): Promise<void> {
  return Promise.resolve();
}

export function history(_page: number): Promise<HistoryEntryView[]> {
  return Promise.resolve([]);
}

export function history_clear(): Promise<void> {
  return Promise.resolve();
}

export function like(_video: VideoSummary): Promise<void> {
  return Promise.resolve();
}

export function unlike(_video_id: string): Promise<void> {
  return Promise.resolve();
}

export function watch_later(_video: VideoSummary): Promise<void> {
  return Promise.resolve();
}

export function export_account(_dest: string): Promise<void> {
  return Promise.resolve();
}

export function import_account(_src: string): Promise<void> {
  return Promise.resolve();
}
