// AUTO-GENERATED via tauri-specta on machines with GTK dev libs. This stub mirrors the shape.
// Regenerated by `pnpm --filter @yoube/desktop gen:contracts` (runs the Tauri binary in debug mode,
// which calls Builder::export -> ../src/bindings.ts). Overwritten on every debug build that reaches
// `run()`; this hand-written copy exists so the TypeScript side typechecks/builds in headless CI.
//
// DEV MOCK DATA: stub bodies below return the canned dataset from
// `src/mocks/data.ts` so `pnpm dev` renders a full UI in a plain browser
// (design review + screenshots). Nothing here ships: specta typegen
// replaces the whole file with real `invoke` calls on GTK machines.

import {
	MOCK_BRANDING,
	MOCK_HISTORY,
	MOCK_SEGMENTS,
	MOCK_USER,
	MOCK_VIDEOS,
	addSubscription,
	cancelJob,
	enqueueJob,
	getSubscriptions,
	listJobs,
	mockChannel,
	mockPlaylist,
	mockPlaylistItems,
	mockPlaylists,
	mockVideo,
	mockVideosForChannel,
	pauseJob,
	removeSubscription,
	resumeJob,
	searchMocks,
	setLiked,
	setWatchLater,
} from "./mocks/data";

export type AppError = string;

export interface PingResponse {
	value: string;
}

export interface VideoSummary {
	id: string;
	title: string;
	channel_id: string;
	channel_title: string;
	duration_s?: number | null;
	view_count?: number | null;
	upload_date?: string | null;
	thumbnail_url?: string | null;
}

export interface Format {
	format_id: string;
	ext: string;
	url?: string | null;
	resolution?: string | null;
	fps?: number | null;
	vcodec?: string | null;
	acodec?: string | null;
	filesize?: number | null;
	tbr?: number | null;
	note?: string | null;
}

export interface Video {
	summary: VideoSummary;
	formats: Format[];
}

export interface Channel {
	id: string;
	title: string;
	description: string;
	thumb_url: string | null;
}

export interface Playlist {
	id: string;
	title: string;
	channel_id: string;
	items: VideoSummary[];
}

export enum Region {
	US = 0,
	GB = 1,
	EG = 2,
	SA = 3,
	DE = 4,
	FR = 5,
	JP = 6,
	BR = 7,
	IN = 8,
	AU = 9,
	CA = 10,
	MX = 11,
	ES = 12,
	IT = 13,
	RU = 14,
	TR = 15,
	ZA = 16,
	NG = 17,
	KR = 18,
	AR = 19,
}

export function ping(): Promise<PingResponse> {
	return Promise.resolve({ value: "pong" });
}

export function get_video(v: string): Promise<Video> {
	return Promise.resolve(mockVideo(v));
}

export function related(v: string): Promise<VideoSummary[]> {
	return Promise.resolve(MOCK_VIDEOS.filter((m) => m.id !== v).slice(0, 8));
}

export function search(q: string, _page: number): Promise<VideoSummary[]> {
	return Promise.resolve(searchMocks(q));
}

export function channel(id: string): Promise<Channel> {
	return Promise.resolve(mockChannel(id));
}

export function channel_videos(
	id: string,
	_page: number,
): Promise<VideoSummary[]> {
	return Promise.resolve(mockVideosForChannel(id));
}

export function playlist(id: string): Promise<Playlist> {
	return Promise.resolve(mockPlaylist(id));
}

export function trending(_region: Region): Promise<VideoSummary[]> {
	return Promise.resolve(MOCK_VIDEOS);
}

// --- AccountService contracts (Task 2.2) ---
// Hand-stubbed mirroring crates/yoube-core/src/services/account.rs.
// Replaced by tauri-specta typegen on machines with the GTK stack.

export interface UserProfile {
	id: number;
	name: string;
	avatar_path: string | null;
}

export interface ChannelRef {
	id: string;
	title: string;
	thumb_url: string | null;
}

export interface AccountPlaylist {
	id: number;
	title: string;
	description: string | null;
	is_watch_later: boolean;
	is_liked: boolean;
	count: number;
}

export interface HistoryEntryView {
	video_id: string;
	title: string;
	channel_title: string | null;
	duration_s: number | null;
	thumb_url: string | null;
	watched_at: string;
	position_s: number;
}

export function current_user(): Promise<UserProfile> {
	return Promise.resolve(MOCK_USER);
}

export function switch_user(_id: number): Promise<void> {
	return Promise.resolve();
}

export function create_user(name: string): Promise<UserProfile> {
	return Promise.resolve({ id: 1, name, avatar_path: null });
}

export function delete_user(_id: number): Promise<void> {
	return Promise.resolve();
}

export function subscriptions(): Promise<ChannelRef[]> {
	return Promise.resolve(getSubscriptions());
}

export function subscribe(
	channel_id: string,
	title: string,
	thumb_url?: string | null,
): Promise<void> {
	addSubscription(channel_id, title, thumb_url);
	return Promise.resolve();
}

export function unsubscribe(channel_id: string): Promise<void> {
	removeSubscription(channel_id);
	return Promise.resolve();
}

export function playlists(): Promise<AccountPlaylist[]> {
	return Promise.resolve(mockPlaylists());
}

export function playlist_items(id: number): Promise<VideoSummary[]> {
	return Promise.resolve(mockPlaylistItems(id));
}

export function playlist_add(_id: number, _video: VideoSummary): Promise<void> {
	return Promise.resolve();
}

export function playlist_remove(id: number, video_id: string): Promise<void> {
	const v = MOCK_VIDEOS.find((m) => m.id === video_id);
	if (v) {
		if (id === 1) setLiked(v, false);
		if (id === 2) setWatchLater(v, false);
	}
	return Promise.resolve();
}

export function history(_page: number): Promise<HistoryEntryView[]> {
	return Promise.resolve(MOCK_HISTORY);
}

export function history_clear(): Promise<void> {
	return Promise.resolve();
}

export function like(video: VideoSummary): Promise<void> {
	setLiked(video, true);
	return Promise.resolve();
}

export function unlike(video_id: string): Promise<void> {
	const v = MOCK_VIDEOS.find((m) => m.id === video_id);
	if (v) setLiked(v, false);
	return Promise.resolve();
}

export function watch_later(video: VideoSummary): Promise<void> {
	setWatchLater(video, true);
	return Promise.resolve();
}

export function export_account(dest: string): Promise<string> {
	return Promise.resolve(dest);
}

export function import_account(_src: string): Promise<void> {
	return Promise.resolve();
}

// --- DownloaderService contracts (Task 3.2) ---
// Hand-stubbed mirroring crates/yoube-core/src/services/downloader.rs +
// yoube-yt-dlp/src/downloader.rs. Replaced by tauri-specta typegen on
// machines with the GTK stack.

export type JobState =
	| "Queued"
	| "Running"
	| "Paused"
	| "Done"
	| "Failed"
	| "Cancelled";

export interface Job {
	id: number;
	video_id: string;
	format_id: string;
	dest_dir: string;
	state: JobState;
	progress_bytes: number;
	total_bytes: number | null;
	eta_s: number | null;
	error: string | null;
}

export type DownloadEvent =
	| {
			kind: "progress";
			id: number;
			bytes: number;
			total: number | null;
			eta_s: number | null;
	  }
	| { kind: "state"; id: number; state: JobState; error: string | null };

export function list_formats(video_id: string): Promise<Format[]> {
	return Promise.resolve(mockVideo(video_id).formats);
}

export function download_enqueue(
	video_id: string,
	format_id: string,
	dest_dir: string,
): Promise<number> {
	return Promise.resolve(enqueueJob(video_id, format_id, dest_dir));
}

export function download_pause(id: number): Promise<void> {
	pauseJob(id);
	return Promise.resolve();
}

export function download_resume(id: number): Promise<void> {
	resumeJob(id);
	return Promise.resolve();
}

export function download_cancel(id: number): Promise<void> {
	cancelJob(id);
	return Promise.resolve();
}

export function download_list(): Promise<Job[]> {
	return Promise.resolve(listJobs());
}

// --- FilterService contracts (Task 4.2) ---
// Hand-stubbed mirroring crates/yoube-core/src/services/filter.rs +
// yoube-filter/src/model.rs. Replaced by tauri-specta typegen on machines
// with the GTK stack.

export type SegmentCategory =
	| "sponsor"
	| "intro"
	| "outro"
	| "selfpromo"
	| "preview"
	| "music_offtopic"
	| "filler"
	| "interaction"
	| "poi_highlight";

export interface Segment {
	category: SegmentCategory;
	start_s: number;
	end_s: number;
	uuid: string;
}

export interface Branding {
	title: string | null;
	thumbnail_url: string | null;
}

export function filter_init(): Promise<number> {
	return Promise.resolve(128400);
}

export function filter_matches(
	_url: string,
	_source_url: string,
): Promise<boolean> {
	return Promise.resolve(false);
}

export function filter_segments_for(_video_id: string): Promise<Segment[]> {
	return Promise.resolve(MOCK_SEGMENTS);
}

export function filter_branding_for(_video_id: string): Promise<Branding> {
	return Promise.resolve(MOCK_BRANDING);
}

// --- DnsBlockService contracts (Task 4.3) ---
// Hand-stubbed mirroring crates/yoube-core/src/services/dns.rs.
// Replaced by tauri-specta typegen on machines with the GTK stack.

export function dns_install(): Promise<number> {
	return Promise.resolve(0);
}

export function dns_uninstall(): Promise<void> {
	return Promise.resolve();
}

export function dns_status(): Promise<string> {
	return Promise.resolve("not_installed");
}

export function dns_refresh(): Promise<number> {
	return Promise.resolve(0);
}

// --- Updater contracts ---
// Hand-stubbed mirroring commands::UpdateInfo. Replaced by tauri-specta
// typegen on machines with the GTK stack.

export interface UpdateInfo {
	available: boolean;
	current: string;
	latest: string | null;
	notes: string | null;
}

export function check_update(): Promise<UpdateInfo> {
	return Promise.resolve({
		available: false,
		current: "0.0.1",
		latest: null,
		notes: null,
	});
}
