/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ChannelIdRouteImport } from './routes/channel.$id'
import { Route as FeedHistoryRouteImport } from './routes/feed.history'
import { Route as FeedLikedRouteImport } from './routes/feed.liked'
import { Route as FeedSubscriptionsRouteImport } from './routes/feed.subscriptions'
import { Route as FeedWatchLaterRouteImport } from './routes/feed.watch-later'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelIdRoute = ChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedHistoryRoute = FeedHistoryRouteImport.update({
  id: '/feed/history',
  path: '/feed/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedLikedRoute = FeedLikedRouteImport.update({
  id: '/feed/liked',
  path: '/feed/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSubscriptionsRoute = FeedSubscriptionsRouteImport.update({
  id: '/feed/subscriptions',
  path: '/feed/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedWatchLaterRoute = FeedWatchLaterRouteImport.update({
  id: '/feed/watch-later',
  path: '/feed/watch-later',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/watch': typeof WatchRoute
  '/channel/$id': typeof ChannelIdRoute
  '/feed/history': typeof FeedHistoryRoute
  '/feed/liked': typeof FeedLikedRoute
  '/feed/subscriptions': typeof FeedSubscriptionsRoute
  '/feed/watch-later': typeof FeedWatchLaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/watch': typeof WatchRoute
  '/channel/$id': typeof ChannelIdRoute
  '/feed/history': typeof FeedHistoryRoute
  '/feed/liked': typeof FeedLikedRoute
  '/feed/subscriptions': typeof FeedSubscriptionsRoute
  '/feed/watch-later': typeof FeedWatchLaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/watch': typeof WatchRoute
  '/channel/$id': typeof ChannelIdRoute
  '/feed/history': typeof FeedHistoryRoute
  '/feed/liked': typeof FeedLikedRoute
  '/feed/subscriptions': typeof FeedSubscriptionsRoute
  '/feed/watch-later': typeof FeedWatchLaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/library'
    | '/results'
    | '/settings'
    | '/users'
    | '/watch'
    | '/channel/$id'
    | '/feed/history'
    | '/feed/liked'
    | '/feed/subscriptions'
    | '/feed/watch-later'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/library'
    | '/results'
    | '/settings'
    | '/users'
    | '/watch'
    | '/channel/$id'
    | '/feed/history'
    | '/feed/liked'
    | '/feed/subscriptions'
    | '/feed/watch-later'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/library'
    | '/results'
    | '/settings'
    | '/users'
    | '/watch'
    | '/channel/$id'
    | '/feed/history'
    | '/feed/liked'
    | '/feed/subscriptions'
    | '/feed/watch-later'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WatchRoute: typeof WatchRoute
  ChannelIdRoute: typeof ChannelIdRoute
  FeedHistoryRoute: typeof FeedHistoryRoute
  FeedLikedRoute: typeof FeedLikedRoute
  FeedSubscriptionsRoute: typeof FeedSubscriptionsRoute
  FeedWatchLaterRoute: typeof FeedWatchLaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$id': {
      id: '/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof ChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/history': {
      id: '/feed/history'
      path: '/feed/history'
      fullPath: '/feed/history'
      preLoaderRoute: typeof FeedHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/liked': {
      id: '/feed/liked'
      path: '/feed/liked'
      fullPath: '/feed/liked'
      preLoaderRoute: typeof FeedLikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/subscriptions': {
      id: '/feed/subscriptions'
      path: '/feed/subscriptions'
      fullPath: '/feed/subscriptions'
      preLoaderRoute: typeof FeedSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/watch-later': {
      id: '/feed/watch-later'
      path: '/feed/watch-later'
      fullPath: '/feed/watch-later'
      preLoaderRoute: typeof FeedWatchLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WatchRoute: WatchRoute,
  ChannelIdRoute: ChannelIdRoute,
  FeedHistoryRoute: FeedHistoryRoute,
  FeedLikedRoute: FeedLikedRoute,
  FeedSubscriptionsRoute: FeedSubscriptionsRoute,
  FeedWatchLaterRoute: FeedWatchLaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
